Drop support for CentOS 7
charmed-hpc/slurmctld-operator pull request #18
Opened 2023-09-22 16:34 UTC by jaimesouza

## Description

Drop support for CentOS 7.

## How was the code tested?

The code was tested locally with LXD containers running Ubuntu 22.04.

## Checklist

- [x] I am the author of these changes, or I have the rights to submit them.
- [ ] I have added the relevant changes to the README and/or documentation.
- [x] I have self reviewed my own code.
- [ ] All requested changes and/or review comments have been resolved.

2023-09-26 14:05 UTC, NucciTheBoss requested changes
Just one minor comment, but other than that, it lgtm @jaimesouza!

2023-09-26 14:05 UTC, NucciTheBoss commented on dispatch
We can remove this custom dispatch script entirely since we are no longer performing the injection to install `epel-release` and `python3` before executing the _charm.py_ script. Once we remove this custom dispatch script, the dispatch script will automatically be generated by Juju when the slurmctld operator is deployed so we do not need to create it ourselves.

2023-09-26 14:27 UTC, jaimesouza commented on dispatch
That is right! Thanks @NucciTheBoss!

2023-09-29 15:37 UTC, NucciTheBoss approved these changes
LGTM! Nice work :tada:

2023-09-29 15:37 UTC, NucciTheBoss approved these changes
LGTM! Nice work :tada:

2023-10-02 12:23 UTC, merged